services:

  frontend:
    build:
      context: ./frontend
    image: moaaz65/deals-store-frontend:v1.0.0
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - frontend-net

  backend:
    build:
      context: ./backend
    image: moaaz65/deals-store-backend:v1.0.0 
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      MYSQL_HOST: mysql-db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - frontend-net
      - backend-net

  mysql-db:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    healthcheck:
    test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
    interval: 10s
    timeout: 5s
    retries: 10
    start_period: 60s
    networks:
      - backend-net

volumes:
  mysql-volume:

networks:
  frontend-net:
  backend-net: