services:

  reverse-proxy:
    build:
      context: ./reverse-proxy
    image: ${DOCKERHUB_USERNAME}/deals-store-reverse-proxy:${IMAGE_TAG}
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - frontend-net

  frontend:
    build:
      context: ./frontend
    image: ${DOCKERHUB_USERNAME}/deals-store-frontend:${IMAGE_TAG}
    restart: unless-stopped
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - frontend-net

  backend:
    build:
      context: ./backend
    image: ${DOCKERHUB_USERNAME}/deals-store-backend:${IMAGE_TAG}
    restart: unless-stopped
    expose:
      - "8000"
    environment:
      MYSQL_HOST: mysql-db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - frontend-net
      - backend-net

  mysql-db:
    build:
      context: ./database
    image: ${DOCKERHUB_USERNAME}/deals-store-mysql:${IMAGE_TAG}
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    networks:
      - backend-net

volumes:
  mysql-volume:

networks:
  frontend-net:
  backend-net:
