---
- name: Update system packages
  dnf:
    name: "*"
    state: latest
    update_cache: true

- name: Install Git
  dnf:
    name: git
    state: present

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: true

- name: Add ec2-user to docker group
  user:
    name: ec2-user
    groups: docker
    append: true
