apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: deals-store

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: moaaz65/deals-store-backend:latest

          ports:
            - containerPort: 8000

          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: deals-store-config
                  key: MYSQL_HOST

            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: deals-store-config
                  key: MYSQL_DATABASE

            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "300m"
              memory: "256Mi"